version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Changed from 8080:3000 to match expected test port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flashcard_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      # Add a properly Base64 encoded JWT secret for Docker
      - JWT_SECRET=VGhpcyBpcyBhIHNlY3VyZSBKV1Qgc2VjcmV0IGtleSBmb3IgZG9ja2VyIGVudmlyb25tZW50
      # Email configuration for MailHog
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=test
      - SPRING_MAIL_PASSWORD=test
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_FROM=noreply@flashcardapp.com
      - APP_EMAIL_VERIFICATION_URL=http://localhost:3000/api/auth/verify-email?token=
    depends_on:
      - db
      - mailhog
    networks:
      - flashcard-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flashcard_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashcard-network
      
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - flashcard-network

networks:
  flashcard-network:
    driver: bridge

volumes:
  postgres_data: